package com.mycompany.testmex;

import java.math.BigDecimal;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Martino Maniero & Alessandro Bergantin
 */
public class Chat extends javax.swing.JFrame {
    public String destinatario;
    public String mittente;
    /**
     * Creates new form chat
     */
    public Chat(String mittente, String destinatario) {
        this.destinatario = destinatario;
        this.mittente = mittente;
        initComponents();
    }
    
    public String[] chat(){
    String[] messaggi = new String[20];
    
    try{  
            // create the mysql insert preparedstatement
            String query = "SELECT testo,mittente,destinatario,iD FROM messaggi WHERE destinatario =? AND mittente =?" +
                           "UNION\n" +
                           "SELECT testo,mittente,destinatario,iD FROM messaggi WHERE destinatario =? AND mittente =?" + "ORDER BY iD";
            
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(query); 
            ps.setString(1,destinatario);
            ps.setString(2,mittente);
            ps.setString(3,mittente);
            ps.setString(4,destinatario);
            ResultSet rs=ps.executeQuery();
            int i = 0;
            while(rs.next()){
            String testomsg = rs.getString("testo");
            String mit = rs.getString("mittente");
            
            messaggi[i] = mit+": "+testomsg;
            //messaggi[i] = testomsg;
            
            i++;
            
            }
            }
        catch(Exception e){ System.out.println(e);} 
    
    return messaggi;
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        messaggio = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("SEND");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        messaggio.setColumns(20);
        messaggio.setRows(5);
        jScrollPane2.setViewportView(messaggio);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = chat();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        jButton2.setText("REFRESH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(256, 256, 256)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String getE()
    {   
        String s = new String();
        try{  
            // create the mysql insert preparedstatement
            String query = "SELECT pubblica FROM utenti WHERE userName =?";
                           
            
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(query); 
            ps.setString(1,destinatario);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
            s = rs.getString("pubblica");
            }
        }
            
        catch(Exception e){ System.out.println(e);} 
    
    return s;
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RSANumerico rsa = new RSANumerico(getE());
        try{  
            // create the mysql insert preparedstatement
            String query = "INSERT INTO messaggi (mittente,destinatario,testo)" + " VALUES (?,?,?)";
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(query);          

            ps.setString (1, mittente);
            ps.setString (2, destinatario);
            ps.setString (3,rsa.cifratura(messaggio.getText()));
          
            // execute the preparedstatement
            ps.execute();
            
            }
        catch(Exception e){ System.out.println(e);} 
        String[] msg = chat();
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = msg;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }});
        jList1.updateUI();
        
        messaggio.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    private void jList1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseMoved
        // TODO add your handling code here:
        String[] msg = chat();
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = msg;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }});
        jList1.updateUI();
    }//GEN-LAST:event_jList1MouseMoved
    * */
    
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int index = jList1.locationToIndex(evt.getPoint());
            if (index >= 0) {
            Object o = jList1.getModel().getElementAt(index);
            String msgInt = o.toString();
            String[] l = msgInt.split(" ");
            String msg = l[1];
            
            MsgDecifrato m = new MsgDecifrato(msg);
            
            m.setVisible(true);}}
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String[] msg = chat();
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = msg;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }});
        jList1.updateUI();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messaggio;
    // End of variables declaration//GEN-END:variables
}
