package com.mycompany.testmex;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Martino Maniero & Alessandro Bergantin
 */
public class Rubrica extends javax.swing.JFrame {
    public String nomeUtente;
    public String destinatario;
    
    public Rubrica(String uname) {
        nomeUtente = uname;
        initComponents();
        }
    
    
    
    public String[] lstUtn(){
    String[] utenti = new String[20];
    try{  
        // create the mysql insert preparedstatement
            String query = "SELECT userName FROM utenti";
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(query);          
            ResultSet rs=ps.executeQuery();
            int i = 0;
            while(rs.next()){
            String nome = rs.getString("userName");
            if(!nome.equals(nomeUtente)) {utenti[i] = nome;}
            i++;
            }
            }
        catch(Exception e){ System.out.println(e);} 
    
    return utenti;
    
    }
    
    public String[] lstMsg(){
    String[] messaggi = new String[20];
    
    try{  
        // create the mysql insert preparedstatement
            String query = "SELECT testo,mittente FROM messaggi WHERE destinatario =?";
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(query); 
            ps.setString(1,nomeUtente);
            ResultSet rs=ps.executeQuery();
            int i = 0;
            while(rs.next()){
            String nome = rs.getString("testo");
            String mit = rs.getString("mittente");
            messaggi[i] = mit+": "+nome;
            //messaggi[i] = nome;
            i++;
            
            }
            }
        catch(Exception e){ System.out.println(e);} 
    
    return messaggi;
    
    }
        
                       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = lstUtn();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = lstMsg();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        jButton3.setText("REFRESH");
        jButton3.setMaximumSize(new java.awt.Dimension(518, 518));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("contacts");

        jLabel2.setText("messages");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(40, 40, 40)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
            // TODO add your handling code here:
            
            if (evt.getClickCount() == 2) {
            int index = jList1.locationToIndex(evt.getPoint());
            if (index >= 0) {
            Object o = jList1.getModel().getElementAt(index);
            destinatario = o.toString();
            Chat c = new Chat(nomeUtente,destinatario);
            c.setTitle("chat with "+destinatario);
            c.setVisible(true);
            
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String[] msg = lstMsg();
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = msg;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }});
        jList2.updateUI();
        
        String[] utn = lstUtn();
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = utn;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }});
        jList1.updateUI();
       
    }//GEN-LAST:event_jButton3ActionPerformed

  

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int index = jList2.locationToIndex(evt.getPoint());
            if (index >= 0) {
            Object o = jList2.getModel().getElementAt(index);
            String msgInt = o.toString();
            String[] l = msgInt.split(" ");
            String msg = l[1];
            MsgDecifrato m = new MsgDecifrato(msg);
            
            m.setVisible(true);}}
    }//GEN-LAST:event_jList2MouseClicked

                                       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
